fixed multiple runs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,6 +27,7 @@ jobs:
     # first, most jobs would duplicate the work of downloading crates from
     # the internet. Populating the cache first ensures that this work only
     # happens once.
+    needs: generate_cache
 
     strategy:
       # By default, this is set to `true`, which means that a single CI job
@@ -282,6 +283,7 @@ jobs:
           rustfmt --check zerocopy-derive/tests/**/*.rs
 
   check_readme:
+    needs: generate_cache
     runs-on: ubuntu-latest
     name: Check README.md
     steps:
@@ -303,6 +305,7 @@ jobs:
           exit $?
 
   check_msrv:
+    needs: generate_cache
     runs-on: ubuntu-latest
     name: Check MSRVs match
     steps:
@@ -342,6 +345,7 @@ jobs:
           fi
 
   check_versions:
+    needs: generate_cache
     runs-on: ubuntu-latest
     name: Check crate versions match
     steps:
@@ -415,7 +419,38 @@ jobs:
           assert-match "$zerocopy_derive_dep_ver" "$zerocopy_derive_targeted_ver" \
             "Same crate version ($zerocopy_derive_dep_ver) found for optional and targeted zerocopy-derive dependency." \
             "Different crate versions found for optional ($zerocopy_derive_dep_ver) and targeted ($zerocopy_derive_targeted_ver) dependency."
+  
+  generate_cache:
+    runs-on: ubuntu-latest
+    name: Generate cache
+    steps:
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
+      - name: Populate cache
+        uses: ./.github/actions/cache
+
+      - name: Download dependencies
+        run: |
+          # Ensure all dependencies are downloaded - both for our crates and for
+          # tools we use in CI. We don't care about these tools succeeding for
+          # two reasons: First, this entire job is best-effort since it's just a
+          # performance optimization. Second, there may be failures due to
+          # issues other than failing to download dependencies (e.g., `cargo
+          # metadata` called with a malformed `Cargo.toml`, build failure in our
+          # own crate or in dependencies, etc). For those reasons, we discard
+          # stderr and ignore status codes.
+          #
+          # For downloading our crates' dependencies in particular, note that
+          # there is no support for doing this directly [1], so we just check
+          # all crates using --tests.
+          #
+          # [1]  https://stackoverflow.com/a/42139535/836390
+          cargo check --workspace --tests            &> /dev/null || true
+          cargo metadata                             &> /dev/null || true
+          cargo install cargo-readme --version 3.2.0 &> /dev/null || true
+          cargo install --locked kani-verifier       &> /dev/null || true
+          cargo kani setup                           &> /dev/null || true
+        
   check-job-dependencies:
     runs-on: ubuntu-latest
     name: Check all-jobs-succeeded depends on all jobs
@@ -460,7 +495,7 @@ jobs:
       # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
       if: failure()
       runs-on: ubuntu-latest
-      needs: [build_test, kani, check_fmt, check_readme, check_msrv, check_versions, check-job-dependencies]
+      needs: [build_test, kani, check_fmt, check_readme, check_msrv, check_versions, generate_cache,check-job-dependencies]
       steps:
         - name: Mark the job as failed
           run: exit 1
